# .github/workflows/deploy.yml

name: Deploy para o GitHub Pages

on:
  push:
    branches:
      - main  # Altere se sua branch principal for outra

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Altere conforme sua necessidade

      - name: Instalar dependências com Yarn
        run: yarn install

      - name: Rodar build com NPM
        run: npm run sass

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # ou ./dist, dependendo do seu projeto
